2024-01-29 21:55:11,796 autoreload 5720 3120 INFO Watching for file changes with StatReloader
2024-01-29 21:59:43,645 autoreload 9528 23168 INFO Watching for file changes with StatReloader
2024-01-29 22:00:20,966 autoreload 9352 19240 INFO Watching for file changes with StatReloader
2024-01-29 22:00:56,682 autoreload 16544 18068 INFO Watching for file changes with StatReloader
2024-01-29 22:01:02,170 autoreload 16544 18068 INFO H:\Usuários\Codes\Alppi\Microservice_1\config\settings.py changed, reloading.
2024-01-29 22:01:02,738 autoreload 1328 21960 INFO Watching for file changes with StatReloader
2024-01-29 22:01:09,163 autoreload 1328 21960 INFO H:\Usuários\Codes\Alppi\Microservice_1\config\settings.py changed, reloading.
2024-01-29 22:01:09,713 autoreload 16720 15576 INFO Watching for file changes with StatReloader
2024-01-29 22:01:22,287 autoreload 16720 15576 INFO H:\Usuários\Codes\Alppi\Microservice_1\config\settings.py changed, reloading.
2024-01-29 22:01:22,791 autoreload 11672 24384 INFO Watching for file changes with StatReloader
2024-01-29 22:01:26,113 autoreload 11672 24384 INFO H:\Usuários\Codes\Alppi\Microservice_1\config\settings.py changed, reloading.
2024-01-29 22:01:26,649 autoreload 19032 19452 INFO Watching for file changes with StatReloader
2024-01-29 22:01:31,006 autoreload 19032 19452 INFO H:\Usuários\Codes\Alppi\Microservice_1\config\settings.py changed, reloading.
2024-01-29 22:01:31,634 autoreload 288 23100 INFO Watching for file changes with StatReloader
2024-01-29 22:01:38,404 autoreload 288 23100 INFO H:\Usuários\Codes\Alppi\Microservice_1\config\settings.py changed, reloading.
2024-01-29 22:01:39,065 autoreload 5964 268 INFO Watching for file changes with StatReloader
2024-01-29 22:01:53,763 basehttp 5964 14244 INFO "GET / HTTP/1.1" 200 10629
2024-01-29 22:01:54,035 log 5964 14244 WARNING Not Found: /favicon.ico
2024-01-29 22:01:54,036 basehttp 5964 14244 WARNING "GET /favicon.ico HTTP/1.1" 404 2110
2024-01-29 22:01:58,911 log 5964 14244 ERROR Internal Server Error: /admin/
Traceback (most recent call last):
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\sessions\backends\base.py", line 187, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\admin\sites.py", line 228, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\admin\sites.py", line 201, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\auth\middleware.py", line 33, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\auth\middleware.py", line 13, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\auth\__init__.py", line 209, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\auth\__init__.py", line 62, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\sessions\backends\base.py", line 53, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\sessions\backends\base.py", line 192, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\sessions\backends\db.py", line 42, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\models\query.py", line 643, in get
    num = len(clone)
          ^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\models\query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

2024-01-29 22:01:58,919 basehttp 5964 14244 ERROR "GET /admin/ HTTP/1.1" 500 202695
2024-01-29 22:02:18,081 autoreload 8304 8172 INFO Watching for file changes with StatReloader
2024-01-29 22:02:19,778 basehttp 8304 17992 INFO "GET / HTTP/1.1" 200 10629
2024-01-29 22:02:24,756 log 8304 17992 WARNING Not Found: /ad]
2024-01-29 22:02:24,757 basehttp 8304 17992 WARNING "GET /ad] HTTP/1.1" 404 2088
2024-01-29 22:02:30,255 log 8304 17992 ERROR Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\sessions\backends\base.py", line 187, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\admin\sites.py", line 409, in login
    if request.method == "GET" and self.has_permission(request):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\admin\sites.py", line 201, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\auth\middleware.py", line 33, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\auth\middleware.py", line 13, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\auth\__init__.py", line 209, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\auth\__init__.py", line 62, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\sessions\backends\base.py", line 53, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\sessions\backends\base.py", line 192, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\sessions\backends\db.py", line 42, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\models\query.py", line 643, in get
    num = len(clone)
          ^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\models\query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "H:\Usuários\Codes\Alppi\venv_ms1\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

2024-01-29 22:02:30,260 basehttp 8304 17992 ERROR "GET /admin/login/ HTTP/1.1" 500 192138
2024-01-29 22:03:56,512 autoreload 15524 22312 INFO Watching for file changes with StatReloader
2024-01-29 22:04:02,379 autoreload 13720 19180 INFO Watching for file changes with StatReloader
2024-01-29 22:05:04,083 autoreload 17280 1524 INFO Watching for file changes with StatReloader
2024-01-29 22:05:22,352 autoreload 19180 11348 INFO Watching for file changes with StatReloader
2024-01-29 22:05:58,521 autoreload 19180 11348 INFO H:\Usuários\Codes\Alppi\Microservice_1\config\settings.py changed, reloading.
2024-01-29 22:05:59,212 autoreload 12236 22160 INFO Watching for file changes with StatReloader
2024-01-29 22:06:40,736 autoreload 1660 9244 INFO Watching for file changes with StatReloader
2024-01-29 22:07:18,692 autoreload 11320 22772 INFO Watching for file changes with StatReloader
2024-01-29 22:07:29,521 autoreload 11320 22772 INFO H:\Usuários\Codes\Alppi\Microservice_1\config\settings.py changed, reloading.
2024-01-29 22:07:30,053 autoreload 23220 11236 INFO Watching for file changes with StatReloader
2024-01-29 22:07:31,316 autoreload 23220 11236 INFO H:\Usuários\Codes\Alppi\Microservice_1\config\settings.py changed, reloading.
2024-01-29 22:07:31,872 autoreload 19212 16056 INFO Watching for file changes with StatReloader
2024-01-29 22:07:33,164 autoreload 19212 16056 INFO H:\Usuários\Codes\Alppi\Microservice_1\config\settings.py changed, reloading.
2024-01-29 22:07:33,691 autoreload 23072 15408 INFO Watching for file changes with StatReloader
2024-01-29 22:08:00,138 autoreload 23072 15408 INFO H:\Usuários\Codes\Alppi\Microservice_1\config\settings.py changed, reloading.
2024-01-29 22:08:00,667 autoreload 3396 17280 INFO Watching for file changes with StatReloader
2024-01-29 22:08:08,420 autoreload 3396 17280 INFO H:\Usuários\Codes\Alppi\Microservice_1\config\settings.py changed, reloading.
2024-01-29 22:08:08,968 autoreload 19996 296 INFO Watching for file changes with StatReloader
2024-01-29 22:08:25,266 autoreload 19996 296 INFO H:\Usuários\Codes\Alppi\Microservice_1\config\urls.py changed, reloading.
2024-01-29 22:08:25,880 autoreload 6472 7884 INFO Watching for file changes with StatReloader
2024-01-29 22:08:29,528 autoreload 6472 7884 INFO H:\Usuários\Codes\Alppi\Microservice_1\config\urls.py changed, reloading.
2024-01-29 22:08:30,184 autoreload 5576 20160 INFO Watching for file changes with StatReloader
2024-01-29 22:08:47,528 autoreload 20420 20076 INFO Watching for file changes with StatReloader
